name = "rolldorado-app-ch"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=rolldorado-app.ch"
HMAC_KEY = "86293349bac584998ae34072b98ac91e7b38fe82faf9ef3c8424810f45fba49c"
COOKIE_NAME = "60z"
PLAY_PATH = "visit-site"
BUTTON_ID = "p8d73d0aa38bb4c85cabe90728b812e1f"
GATE_SALT = "a9c6a1c04271e281"
